image:
  repository: artifactory.dagility.com/docker/vdxap-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdxap-backend-habitat-live.dagility.com
    paths:
    - /
serviceAccount:
  create: false
